from __future__ import annotations

import argparse
import re
from pathlib import Path


def slugify(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]+", "_", name.strip().lower()).strip("_") or "new_agent_app"


def create_application(name: str, task: str, base_dir: str | Path = "applications") -> Path:
    slug = slugify(name)
    root = Path(base_dir) / slug
    root.mkdir(parents=True, exist_ok=True)
    (root / "app.py").write_text(
        f'''from clawflow.sdk import ClawFlowApp


APP = ClawFlowApp(
    name="{slug}",
    task="{task}",
    auto_approve=True,
)


def main():
    return APP.run()


if __name__ == "__main__":
    print(main().final_answer)
''',
        encoding="utf-8",
    )
    (root / "README.md").write_text(
        f"""# {name}

This application was generated by `scripts/create_application_template.py`.

It is intentionally not a standalone demo: it uses `ClawFlowApp`, which calls the unified `AgentRuntime` with planner, executor, tools, governance, memory, trace and checkpoint.

Task:

```text
{task}
```
""",
        encoding="utf-8",
    )
    return root


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate a Runtime-backed ClawFlow application template.")
    parser.add_argument("name")
    parser.add_argument("task")
    args = parser.parse_args()
    print(create_application(args.name, args.task))


if __name__ == "__main__":
    main()
